name: trigger-demo


on:
  push:
    branches: [ "maaster" ]       
  pull_request:
  workflow_dispatch:           
jobs:

  trigger-demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
   
     
